### ISSUE TITLE
Missing include files

### ISSUE THREAD

**Issue by robmobz** [procule/IRAnalyzer#1]
The included header files call for AnalyzerHelpers.h and Analyzer.h which are not present.

Please help.

**Comment by procule** [comment]
Hi, sorry for the delay. I didn't see your comment until today.

You will need the SaleaeAnalyzer SDK from their website. 
Here is the link: http://downloads.saleae.com/SDK/SaleaeAnalyzerSdk-1.1.14.zip

Good luck,

O.
